### ISSUE TITLE
Oniguruma's \h matches hex digits, not horizontal whitespace

### ISSUE THREAD

**Issue by slevithan** [antfu/oniguruma-to-js#2]
### Describe the bug

Currently `oniguruma-to-js` interprets `\h` as `[ \t]` (see [here](https://github.com/antfu/oniguruma-to-js/blob/0c180749e851a2fa4d4594cbbcbe639dcf67254b/test/lowering.test.ts#L116-L124)), but in fact it should be equivalent to `[0-9A-Fa-f]`. Inverted `\H` should be equivalent to `[^0-9A-Fa-f]`.

### Reproduction

Test at rubular.com, etc.

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Nice found. Thanks!

**Comment by antfu** [comment]
I think for https://github.com/microsoft/vscode-oniguruma at least, `\h` is horizontal whitespace. Changing `[0-9A-Fa-f]` casing mismatches instead for my tests.
